### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by sebbu2** [skariel/keypub#4]
I registered 2 ssh keys to my email adress, and then i can't check `whoami` or `unregister` or any other command

**Comment by skariel** [comment]
thanks for reporting. The DB schema and the code for registering the keys was fine. The problem was in the `whoami` and `unregister` commands. Now fixed via 0d68c3d7198a080fa6d1383b5ef7a88e66d86039.

Closing this for now, feel free to reopen if problem persists

**Comment by sebbu2** [comment]
`kp unregister` says `Error: multiple registrations found for this fingerprint`

`kp whoami` says `Error: multiple emails found for fingerprint: SHA256:******`

Maybe an option to kp to specify the email in addition to the key ?

**Comment by skariel** [comment]
there are two cases that need fixing:
1. multiple fingerprints per mail (solved)
2. multiple mails per fingerprint
according to the description, I assumed this issue is about case (1), and I believe that is solved.
regarding case (2) -- I opened a new issue: #13 . My current thinking is that although it is technically possible to have multiple mail addresses per fingerprint, it would be better to allow only a single one. Let's continue discussing in the new issue, I wrote my reasoning there
